### ISSUE TITLE
Letterforms feedback

### ISSUE THREAD

**Issue by LisaHuang2017** [batsimadz/Sankofa-Display#3]
There has been significant progress since the previous version! 

From the status of Sankofa Display as of Dec. 07, 2023, here are some feedback on the letterforms and details (marked in Green in the PDF attached below, Red being comments on the spacing of some letters):
[Sankofa_Lisa_231207.pdf](https://github.com/batsimadz/Sankofa-Display/files/13601944/Sankofa_Lisa_231207.pdf)

(You can mark each point of this checklist if/when these are done)
2. [ ] j and r - the dot could be more center aligned. And the bottom could be shorter?
3. [ ] k - it looks very narrow compared to most letters. Maybe it needs to have another construction? I saw that you did something different for /kgreenlandic. This could be a nice solution for the /k, with a longer ascender of course.
4. [ ] y - I don't see why the /y couldn't be just a /v with a descender? The triangle part in /y looks much smaller than /v, so brings the impression of a smaller letter when placed into words.
5. [ ] z - every single letter in Sankofa has a strong personality and don't follow the "conventional" structure. Maybe letter /z could have more personality as well? 
6. [ ] figures (mentioned in the [Numerals feedback issue](https://github.com/batsimadz/Sankofa-Display/issues/2))
7. [ ] hook (diacritic) - I believe it could be shorter, thus be smaller and better aligned with the other diacritics
8. [ ] tilde - the /tilde looks super long, it could be shorter on its edges to have this "wave" shape specific to the tilde
9. [ ] ogonek - maybe it could be a vertical + horizontal instead of a diagonal + horizontal ? So it is more geometric and simplified? 
10. [ ] Alpha-latin - it took me some time to identify that letter as such. It may need some further explorations to find the right structure. Something like what I sketched in the PDF, or something more like a loop? 
11. [ ] Beta-latin - I don't think that the bottom "serif" is very useful here. Or, it may need to be longer to it looks very intentional and "here".
12. [ ] cedilla (diacritic) - Looking at the forms of letters with which the /cedilla is used with, there could be two forms of /cedilla: one that is connected with the letter, and another that only has that "hook", so it is not literally attached to the letter. You can have a /cedilla.ss01 or /cedilla.alt for combinations with letters without bottom horizontal stroke like /C (also /H).
13. [ ] Chi-latin - it could be wider, almost like the /X
14. [ ] diacritics on top of /D letters - they should be center aligned, not aligned to the bottom tip
15. [ ] Estroke - to avoid a clash between the stroke and the middle triangle, it would be better to modify the triangle just on this /Estroke, plus rotate the stroke a bit more? 
16. [ ] Hturned - be careful that its top doesn't go beyond the capital height!
17. [ ] Iogonek - the ogonek is a part that starts from the bottom right part of a letter.
18. [ ] Jstroke - for this letter only, maybe the dot could be removed so there is more space for the stroke? 
19. [ ] Khook - maybe longer hook, or a different orientation of the hook here, can help identifying that letter as a Khook?
20. [ ] commaaccentcomb - it looks too dark and too long compared to the other diacritics (especially compared next to a /macron or /circumflex)
21. [ ] Nlongrightleg - maybe a different construction for that? 
22. [ ] Omega-latin - same as 21. 
23. [ ] Germandbls - the loop should sit on the baseline
24. [ ] Tdiagonalstroke - the stroke could be rotated a bit more, to have more clarity 
25. [ ] Upsilon-latin - I'm not sure that this can be recognised as an Upsilon... it usually is more like a /Y or a /V. What does the other people think?
26. [ ] Gamma-latin - the loop can get to the descender level, so it really looks different from a potential /V
27. [ ] Vturned - why isn't it the /V upside down? 
28. [ ] astroke - same comment as for Estroke (15).

**Comment by batsimadz** [comment]
2. [✅ ] j and r - the dot could be more center aligned. And the bottom could be shorter?
3. [✅ ] k - it looks very narrow compared to most letters. Maybe it needs to have another construction? I saw that you did something different for /kgreenlandic. This could be a nice solution for the /k, with a longer ascender of course.
4. [✅ ] y - I don't see why the /y couldn't be just a /v with a descender? The triangle part in /y looks much smaller than /v, so brings the impression of a smaller letter when placed into words.
5. [✅ ] z - every single letter in Sankofa has a strong personality and don't follow the "conventional" structure. Maybe letter /z could have more personality as well?
6. [ ✅] figures (mentioned in the https://github.com/batsimadz/Sankofa-Display/issues/2)
7. [ ✅] hook (diacritic) - I believe it could be shorter, thus be smaller and better aligned with the other diacritics
8. [✅ ] tilde - the /tilde looks super long, it could be shorter on its edges to have this "wave" shape specific to the tilde
9. [✅ ] ogonek - maybe it could be a vertical + horizontal instead of a diagonal + horizontal ? So it is more geometric and simplified?
10. [✅ ] Alpha-latin - it took me some time to identify that letter as such. It may need some further explorations to find the right structure. Something like what I sketched in the PDF, or something more like a loop?
11. [✅ ] Beta-latin - I don't think that the bottom "serif" is very useful here. Or, it may need to be longer to it looks very intentional and "here".
12. [✅ ] cedilla (diacritic) - Looking at the forms of letters with which the /cedilla is used with, there could be two forms of /cedilla: one that is connected with the letter, and another that only has that "hook", so it is not literally attached to the letter. You can have a /cedilla.ss01 or /cedilla.alt for combinations with letters without bottom horizontal stroke like /C (also /H).
13. [✅ ] Chi-latin - it could be wider, almost like the /X
14. [✅ ] diacritics on top of /D letters - they should be center aligned, not aligned to the bottom tip
15. [✅ ] Estroke - to avoid a clash between the stroke and the middle triangle, it would be better to modify the triangle just on this /Estroke, plus rotate the stroke a bit more?
16. [✅] Hturned - be careful that its top doesn't go beyond the capital height!
17. [✅ ] Iogonek - the ogonek is a part that starts from the bottom right part of a letter.
18. [✅ ] Jstroke - for this letter only, maybe the dot could be removed so there is more space for the stroke?
19. [✅ ] Khook - maybe longer hook, or a different orientation of the hook here, can help identifying that letter as a Khook?
20. [✅ ] commaaccentcomb - it looks too dark and too long compared to the other diacritics (especially compared next to a /macron or /circumflex)
21. [✅ ] Nlongrightleg - maybe a different construction for that?
22. [✅ ] Omega-latin - same as 21.
23. [✅ ] Germandbls - the loop should sit on the baseline
24. [ ✅] Tdiagonalstroke - the stroke could be rotated a bit more, to have more clarity
25. [ ] Upsilon-latin - I'm not sure that this can be recognised as an Upsilon... it usually is more like a /Y or a /V. What does the other people think?
26. [✅] Gamma-latin - the loop can get to the descender level, so it really looks different from a potential /V
27. [✅ ] Vturned - why isn't it the /V upside down?
28. [✅  ] astroke - same comment as for Estroke (15).
